"""Generate menu-only glyphs and icons from the supplied UI reference.

All inputs and outputs belong to the current project. No runtime readings,
menu numbers or device settings are part of the artwork.
"""
from argparse import ArgumentParser
from pathlib import Path
import hashlib

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "tools/ui_reference/chumaoli/二级页面"
RETURN_REFERENCE = ROOT / "tools/ui_reference/return_home/返回主页_3倍.png"
OUTPUT = ROOT / "CH584_V1_0_1/APP/include/ui_menu_assets.h"
TEXT = """地址分区组网测试设备绑定安装调试上传设置其他信息汇总返回主页
分站号本机保存并重启不开始重置已的名称一键目前扫描到蓝牙总数
错误警报电压异常恢复出厂确认功率通信亮屏时间状态开秒中继无更改为
请按键名称信号解绑个次序成功比率存：:?"""
REFERENCE_NAMES = ["01_地址分区.png", "02_组网测试.png", "03_探头标定.png",
                   "04_安装调试.png", "05_上传设置.png", "06_其它设置.png",
                   "07_初锚力值.png", "08_返回主页.png"]


def pack(image):
    stride = (image.width + 7) // 8
    bits = bytearray(stride * image.height)
    for y in range(image.height):
        for x in range(image.width):
            if image.getpixel((x, y)):
                bits[y * stride + x // 8] |= 1 << (x % 8)
    return bits


def array(name, image):
    bits = pack(image)
    lines = ["    " + ", ".join(f"0x{value:02x}" for value in bits[i:i + 16])
             for i in range(0, len(bits), 16)]
    return f"static const uint8_t {name}[] = {{\n" + ",\n".join(lines) + "\n};\n"


def glyph(char, path, size):
    scale = 4
    face = ImageFont.truetype(str(path), size * scale)
    advance = round(face.getlength(char) / scale)
    canvas = Image.new("L", (advance * scale, (size + 2) * scale), 0)
    ImageDraw.Draw(canvas).text((0, (size - 1) * scale), char, anchor="ls",
                               font=face, fill=255)
    image = canvas.resize((advance, size + 2), Image.Resampling.LANCZOS)
    return image.point(lambda pixel: 255 if pixel >= 140 else 0, mode="1")


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, default=Path("C:/Windows/Fonts/msyhbd.ttc"))
    args = parser.parse_args()
    chars = sorted(set(TEXT.replace("\n", "") + "0123456789-%. dbBmV"))
    parts = ["/* Generated by tools/generate_menu_assets.py; XBMP, LSB first. */\n",
             "#ifndef UI_MENU_ASSETS_H\n#define UI_MENU_ASSETS_H\n#include <stdint.h>\n",
             "typedef struct { uint16_t code; uint8_t width; const uint8_t *bits; } ui_menu_glyph_t;\n"]
    for size in (16, 18):
        images = [(char, glyph(char, args.font, size)) for char in chars]
        for char, image in images:
            parts.append(array(f"ui_menu_{size}_{ord(char):04x}", image))
        parts.append(f"static const ui_menu_glyph_t ui_menu_glyphs_{size}[] = {{\n")
        parts.extend(f"    {{0x{ord(char):04x}, {image.width}u, ui_menu_{size}_{ord(char):04x}}},\n"
                     for char, image in images)
        parts.append("};\n")
    # Crop only static symbols. The screenshot labels/readings are not copied.
    nav_reference = Image.open(REFERENCE / REFERENCE_NAMES[-1]).convert("L")
    for index, name in enumerate(REFERENCE_NAMES):
        reference = Image.open(REFERENCE / name).convert("L")
        top = 12 + 19 * index
        nav = nav_reference.crop((14, top, 27, top + 13)).point(
            (lambda p: 255 if p >= 128 else 0) if index == 7 else
            (lambda p: 255 if p < 128 else 0), "1")
        title = reference.crop((118, 10, 147, 37)).point(lambda p: 255 if p >= 128 else 0, "1")
        parts.append(array(f"ui_menu_nav_{index}", nav))
        parts.append(array(f"ui_menu_title_{index}", title))
    for name, index, bounds in (
            ("address", 0, (324, 73, 371, 125)),
            ("other", 5, (326, 68, 372, 126))):
        detail = Image.open(REFERENCE / REFERENCE_NAMES[index]).convert("L").crop(bounds)
        detail = detail.point(lambda p: 255 if p >= 128 else 0, "1")
        parts.append(array(f"ui_menu_detail_{name}", detail))
    # This confirmation page is entirely static. Keep the supplied typography,
    # house symbols and brand lines; the current sidebar is drawn separately.
    reference = Image.open(RETURN_REFERENCE).convert("L")
    if reference.size != (1152, 504):
        raise ValueError("Return-home reference must be the supplied 3x 384x168 image")
    reference = reference.resize((384, 168), Image.Resampling.NEAREST)
    return_page = reference.crop((113, 1, 379, 167))
    return_page = return_page.point(lambda p: 255 if p >= 128 else 0, "1")
    parts.append(array("ui_menu_return_page", return_page))
    parts.append("static const uint8_t *const ui_menu_nav_icons[] = {\n    " +
                 ", ".join(f"ui_menu_nav_{i}" for i in range(8)) + "\n};\n")
    parts.append("static const uint8_t *const ui_menu_title_icons[] = {\n    " +
                 ", ".join(f"ui_menu_title_{i}" for i in range(8)) + "\n};\n#endif\n")
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"Generated {OUTPUT}: {len(chars)} glyphs in each size, 8 icon pairs")
    print("sha256:", hashlib.sha256(OUTPUT.read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
