"""Generate the home-page wireless XBMP icons in the current project."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CH584_V1_0_1/APP/include/ui_wireless_assets.h"
WIDTH, HEIGHT = 29, 21
COMPACT_WIDTH, COMPACT_HEIGHT = 21, 17
STRONG = (
    "........#####........",
    ".....###########.....",
    "...#####.....#####...",
    ".####...........####.",
    "###...............###",
    ".....................",
    ".......#######.......",
    ".....###########.....",
    "...####.......####...",
    "..###...........###..",
    ".....................",
    ".........###.........",
    ".......#######.......",
    "......###...###......",
    "..........#..........",
    ".........###.........",
    "..........#..........",
)
UNKNOWN = (
    ".....................",
    ".....................",
    ".....................",
    ".......#######.......",
    ".......##...##.......",
    "............##.......",
    "...........###.......",
    "..........###........",
    ".........###.........",
    ".........##..........",
    ".....................",
    ".........##..........",
    ".........##..........",
    ".....................",
    ".....................",
    ".....................",
    ".....................",
)


def pack(rows, width, height):
    assert len(rows) == height and all(len(row) == width for row in rows)
    stride = (width + 7) // 8
    bits = bytearray(stride * height)
    for y, row in enumerate(rows):
        for x, pixel in enumerate(row):
            if pixel == "#":
                bits[stride * y + x // 8] |= 1 << (x % 8)
    return bits


def large_icon(level):
    """Concentric round arcs, with an independently rounded dot below them."""
    rows = []
    for y in range(HEIGHT):
        row = []
        for x in range(WIDTH):
            dx, dy = x - WIDTH // 2, 21.5 - y
            distance = dx * dx + dy * dy
            arcs = ((20, 22), (14, 16), (8, 10))
            ink = dy >= abs(dx) and any(low * low <= distance <= high * high
                for low, high in arcs[3 - (level or 3):])
            ink = ink or dx * dx + (y - 18) * (y - 18) <= 4
            if level == 0:
                # Cover the skipped columns at shallow steps: a continuous slash.
                slash_x = WIDTH - 2 - y * (WIDTH - 4) // (HEIGHT - 1)
                previous_x = WIDTH - 2 - max(0, y - 1) * (WIDTH - 4) // (HEIGHT - 1)
                ink = ink or slash_x <= x <= min(WIDTH - 1, previous_x + 1)
            row.append("#" if ink else ".")
        rows.append("".join(row))
    return rows


def main():
    icons = []
    compact_icons = []
    for level in range(4):
        rows = list(STRONG)
        if level in (1, 2):
            # Keep the inter-arc gaps when hiding outer signal levels.
            hidden_rows = 6 if level == 2 else 11
            rows[:hidden_rows] = ["." * COMPACT_WIDTH] * hidden_rows
        if level == 0:
            # A strike through the full icon means no signal, not strong signal.
            for y in range(COMPACT_HEIGHT):
                row = list(rows[y])
                slash_x = COMPACT_WIDTH - 2 - y
                row[slash_x] = row[slash_x + 1] = "#"
                rows[y] = "".join(row)
        compact_icons.append(pack(rows, COMPACT_WIDTH, COMPACT_HEIGHT))
        icons.append(pack(large_icon(level), WIDTH, HEIGHT))
    compact_icons.append(pack(UNKNOWN, COMPACT_WIDTH, COMPACT_HEIGHT))
    # Center the existing fallback mark without changing its meaning.
    large_unknown = ["." * WIDTH] * 2 + ["...." + row + "...." for row in UNKNOWN] + ["." * WIDTH] * 2
    icons.append(pack(large_unknown, WIDTH, HEIGHT))
    parts = [
        "/* Generated by tools/generate_wireless_assets.py; XBMP, LSB first. */\n",
        "#ifndef UI_WIRELESS_ASSETS_H\n#define UI_WIRELESS_ASSETS_H\n#include <stdint.h>\n",
        f"#define UI_WIRELESS_WIDTH {WIDTH}u\n#define UI_WIRELESS_HEIGHT {HEIGHT}u\n",
        f"#define UI_WIRELESS_COMPACT_WIDTH {COMPACT_WIDTH}u\n#define UI_WIRELESS_COMPACT_HEIGHT {COMPACT_HEIGHT}u\n",
        f"static const uint8_t ui_wireless_icons[5][{((WIDTH + 7) // 8) * HEIGHT}] = {{\n",
    ]
    for bits in icons:
        parts.append("    {" + ", ".join(f"0x{value:02x}" for value in bits) + "},\n")
    parts.append("};\nstatic const uint8_t ui_wireless_compact_icons[5][51] = {\n")
    for bits in compact_icons:
        parts.append("    {" + ", ".join(f"0x{value:02x}" for value in bits) + "},\n")
    parts.append("};\n#endif\n")
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"Generated {OUTPUT}: no signal, weak, medium, strong, unknown")


if __name__ == "__main__":
    main()
