"""Generate the home-page wireless XBMP icons in the current project."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CH584_V1_0_1/APP/include/ui_wireless_assets.h"
WIDTH, HEIGHT = 13, 11
STRONG = (
    ".###########.",
    "###.......###",
    "##.........##",
    "...#######...",
    "..###...###..",
    "..##.....##..",
    ".....###.....",
    "....##.##....",
    ".............",
    ".....###.....",
    ".....###.....",
)
UNKNOWN = (
    ".............",
    "....#####....",
    "....#...#....",
    "........#....",
    ".......##....",
    "......##.....",
    "......#......",
    ".............",
    "......#......",
    ".............",
    ".............",
)


def pack(rows):
    assert len(rows) == HEIGHT and all(len(row) == WIDTH for row in rows)
    bits = bytearray(2 * HEIGHT)
    for y, row in enumerate(rows):
        for x, pixel in enumerate(row):
            if pixel == "#":
                bits[2 * y + x // 8] |= 1 << (x % 8)
    return bits


def main():
    icons = []
    for level in range(4):
        rows = list(STRONG)
        if level in (1, 2):
            rows[:3 if level == 2 else 6] = ["." * WIDTH] * (3 if level == 2 else 6)
        if level == 0:
            # A strike through the full icon means no signal, not strong signal.
            for y in range(HEIGHT):
                row = list(rows[y])
                row[11 - y] = "#"
                rows[y] = "".join(row)
        icons.append(pack(rows))
    icons.append(pack(UNKNOWN))
    parts = [
        "/* Generated by tools/generate_wireless_assets.py; XBMP, LSB first. */\n",
        "#ifndef UI_WIRELESS_ASSETS_H\n#define UI_WIRELESS_ASSETS_H\n#include <stdint.h>\n",
        "#define UI_WIRELESS_WIDTH 13u\n#define UI_WIRELESS_HEIGHT 11u\n",
        "static const uint8_t ui_wireless_icons[5][22] = {\n",
    ]
    for bits in icons:
        parts.append("    {" + ", ".join(f"0x{value:02x}" for value in bits) + "},\n")
    parts.append("};\n#endif\n")
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"Generated {OUTPUT}: no signal, weak, medium, strong, unknown")


if __name__ == "__main__":
    main()
